/*
 * generated by Xtext
 */
package org.nanosite.xtendency.tracer.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TracingExecutionContextUiModule extends org.nanosite.xtendency.tracer.ui.AbstractTracingExecutionContextUiModule {
	public TracingExecutionContextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
