/*
 * generated by Xtext
 */
package org.nanosite.xtendency.tracer;

import org.nanosite.xtendency.tracer.scoping.ExecutionContextScopeProvider;
import org.nanosite.xtendency.tracer.scoping.XtendClassGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TracingExecutionContextRuntimeModule extends org.nanosite.xtendency.tracer.AbstractTracingExecutionContextRuntimeModule {
	public java.lang.Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return XtendClassGlobalScopeProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return ExecutionContextScopeProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
		return ExecutionContextScopeProvider.class;
	}
}
