/*
* generated by Xtext
*/
package org.nanosite.xtendency.tracer;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TracingExecutionContextStandaloneSetup extends TracingExecutionContextStandaloneSetupGenerated{

	public static void doSetup() {
		new TracingExecutionContextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

