/*
 * generated by Xtext
 */
package org.nanosite.xtendency.tracer.ui.contentassist

import org.nanosite.xtendency.tracer.ui.contentassist.AbstractTracingExecutionContextProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TracingExecutionContextProposalProvider extends AbstractTracingExecutionContextProposalProvider {
}
