/*
 * generated by Xtext
 */
package org.nanosite.xtendency.tracer.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RunConfUiModule extends org.nanosite.xtendency.tracer.ui.AbstractRunConfUiModule {
	public RunConfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
