/*
 * generated by Xtext
 */
package org.nanosite.xtendency.tracer.ui.contentassist

import org.nanosite.xtendency.tracer.ui.contentassist.AbstractRunConfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RunConfProposalProvider extends AbstractRunConfProposalProvider {
}
