/*
 * generated by Xtext
 */
package org.nanosite.xtendency.tracer;

import org.nanosite.xtendency.tracer.scoping.RunConfigurationScopeProvider;
import org.nanosite.xtendency.tracer.scoping.XtendClassGlobalScopeProvider;

import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RunConfRuntimeModule extends org.nanosite.xtendency.tracer.AbstractRunConfRuntimeModule {
	public java.lang.Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return XtendClassGlobalScopeProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return RunConfigurationScopeProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
		return RunConfigurationScopeProvider.class;
	}
}
