/*
* generated by Xtext
*/
package org.nanosite.xtendency.tracer;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RunConfStandaloneSetup extends RunConfStandaloneSetupGenerated{

	public static void doSetup() {
		new RunConfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

